# api/config/api_platform/resources.yaml
api_platform:
  defaults:
    item_operations: ~
    collection_operations: ~
#  App\Entity\User:
#    - operations:
#        ApiPlatform\Metadata\GetCollection: ~
#        ApiPlatform\Metadata\Get: ~
#    - operations:
#        ApiPlatform\Metadata\GetCollection:
#          uriTemplate: /users
#          itemUriTemplate: /users/{id}
#        ApiPlatform\Metadata\Get:
#          uriTemplate: /users/{id}