@startuml

entity User {
    id: int <<generated>>
    uuid: uuid <<generated>>
    email: string
    password
}

entity Role {
    *id : number <<generated>>
    *uuid : uuid <<generated>>
}

User }|..|| Role
'Entity03 }o..o| Entity04
'Entity05 ||--o{ Entity06
'Entity07 |o--|| Entity08
@enduml